# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RelayUIDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RelayMainWindow(object):
    def setupUi(self, RelayMainWindow):
        RelayMainWindow.setObjectName("RelayMainWindow")
        RelayMainWindow.resize(718, 364)
        self.centralwidget = QtWidgets.QWidget(RelayMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.telemetryGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.telemetryGroupBox.setObjectName("telemetryGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.telemetryGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.telemetryTextBrowser = QtWidgets.QTextBrowser(self.telemetryGroupBox)
        self.telemetryTextBrowser.setObjectName("telemetryTextBrowser")
        self.verticalLayout.addWidget(self.telemetryTextBrowser)
        self.horizontalLayout.addWidget(self.telemetryGroupBox)
        self.commandsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.commandsGroupBox.setObjectName("commandsGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.commandsGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.commandsTextBrowser = QtWidgets.QTextBrowser(self.commandsGroupBox)
        self.commandsTextBrowser.setObjectName("commandsTextBrowser")
        self.verticalLayout_2.addWidget(self.commandsTextBrowser)
        self.horizontalLayout.addWidget(self.commandsGroupBox)
        RelayMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RelayMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName("menubar")
        RelayMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RelayMainWindow)
        self.statusbar.setObjectName("statusbar")
        RelayMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RelayMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RelayMainWindow)

    def retranslateUi(self, RelayMainWindow):
        _translate = QtCore.QCoreApplication.translate
        RelayMainWindow.setWindowTitle(_translate("RelayMainWindow", "Cosmic KSP Relay"))
        self.telemetryGroupBox.setTitle(_translate("RelayMainWindow", "Telemetry"))
        self.commandsGroupBox.setTitle(_translate("RelayMainWindow", "Commands"))
